[package]
name = "rustcrawler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
reqwest = { version = "0.11.11", features = ["blocking"] }
select = "0.5.0"